### ISSUE TITLE
why are US DOT Numbers not reported?

### ISSUE THREAD

**Issue by aherman-volpe** [s87jackson/rfars#13]
# Description
Why are the US DOT numbers recorded as "Not Reported" or NA in the prepped flat file? The raw data files (specifically the Vehicle data file from the website) record actual US DOT numbers. So far, I haven't been able to identify the source of the transformation:

1. I can't identify the raw file that records MCARR this way (neither the vehiclesf nor vehicle files)
2. I can't identify the source of the issue in the preparation script: https://github.com/s87jackson/rfars/blob/master/R/prep_fars.R

# Data sources

1. In the rfars flat file, see MCARR_I2 values when MCARR_I1 == US DOT.
2. In the NHTSA file download, see the Vehicle file in the 2021 National CSV zip file: https://www.nhtsa.gov/file-downloads?p=nhtsa/downloads/FARS/2021/National/

**Comment by s87jackson** [comment]
This has been fixed. Note that USDOT numbers are in mcarr_i2 and mcarr_id
