### ISSUE TITLE
Downloading data from before 2016

### ISSUE THREAD

**Issue by aarewalt** [s87jackson/rfars#14]
Hi!

I'm attempting to load FARS data from 2014-2021. I seem to have no issue loading 2016-2021, but cannot download 2014-2015. This is the process and error I am seeing: 

myFARS1 <- get_fars(years = 2014)

trying URL 'https://static.nhtsa.gov/nhtsa/downloads/FARS/2014/National/FARS2014NationalSAS.zip'
Content type 'application/x-zip-compressed' length 40663155 bytes (38.8 MB)
downloaded 38.8 MB

Error: 'C:/Users/User/AppData/Local/Temp/RtmpQphKHx/FARS data/raw/2014/' does not exist.

This might be something I am experiencing only on my end. Any feedback/assistance would be appreciated!

**Comment by s87jackson** [comment]
Hi, @aarewalt, it's not just you, NHTSA changed the file structure of their 2011-2016 files (just added another folder layer). I've uploaded a patch to Github and submitted an updated package to CRAN.

**Comment by aarewalt** [comment]
Thanks for your help @s87jackson! I'm still getting an error when downloading data from before 2016. Here is the error message: 
"Error in file(con, "rb") : cannot open the connection
In addition: Warning message:
In file(con, "rb") :
  cannot open file 'C:/Users/allyr/AppData/Local/Temp/RtmpEXbQcP/FARS data/raw/2014': Permission denied"
Do you have any insight on this?
