### ISSUE TITLE
get_fars' dir content is fully reused if "years" param partially matches existing downloads

### ISSUE THREAD

**Issue by katrinleinweber** [s87jackson/rfars#18]
When one doesn't remove a non-tmp `FARS data` directory between `get_fars()`  usages with different `years` values, the full `FARS data` content is being reused:

```R
wd <- getwd()
data1 <- get_fars(years = 2019:2020, proceed = T, dir = wd)
data2 <- get_fars(years = 2019, proceed = T, dir = wd)
dim(data1$flat) == dim(data2$flat)
[1] TRUE TRUE
```

Shouldn't `data2` be much smaller?

**Comment by s87jackson** [comment]
You're right, but it would require reading the data file and checking the years before asking the user what they'd like to do - reading that file takes a long time, so I'd like to avoid that. I added a printed note that warns the user that `years `is ignored if `cache `is specified
