### ISSUE TITLE
get_fars(years = 2012) fails with "Error in file(con, "r") : invalid 'description' argument"

### ISSUE THREAD

**Issue by katrinleinweber** [s87jackson/rfars#19]
In [vignettes/Counts.Rmd](https://github.com/s87jackson/rfars/blob/3dc338ca36ec5b506e08daa6f01a4b519d05f4ee/vignettes/Counts.Rmd), the first download fails for both 2012 & 2013 for me, with the above error.

2014 works fine.

**Comment by s87jackson** [comment]
This is because these two years have corrupt SAS format catalog files. The workaround had a bug but it has been fixed.
